// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceretetqpbwupoevhhym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcmV0ZXRxcGJ3dXBvZXZoaHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTgyNzUsImV4cCI6MjA3MTMzNDI3NX0.C97WdfFhS5txHoZWwO5BvB4-j3ThHafxkG1zLOlteuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});